### ISSUE TITLE
how can add new firmware  that the karonte.py can run

### ISSUE THREAD

**Issue by kiki916** [ucsb-seclab/karonte#7]
If I want to add new firmware, how can I get the json file that the karonte.py can run?

**Comment by tower111** [comment]
If I want to add new firmware, how can I get the json file that the karonte.py can run?   I have this problem too.

Thanks

**Comment by badnack** [comment]
You will have to write the JSON for Karonte. You can refer to the example json in the repo and build from itit. Let me know if you need help with some of the options.

**Comment by badnack** [comment]
No updates.. closing the issue
