### ISSUE TITLE
Does this tool handle aarch64 binaries?

### ISSUE THREAD

**Issue by behnamben** [ucsb-seclab/karonte#8]
Does your dataset include firmware for ARMv8 processors? and if there is, how it performed on them? 
I'm asking this question because the addressing mechanism in aarch64 binaries is different where the program counter register no longer exists instead there are address pages.
when I was testing angr against handcrafted programs based on aarch64 binaries, it couldn't construct a proper CFG and DDG and.

**Comment by badnack** [comment]
Hi, karonte is based on angr, and it does support aarch64. However, if you
are experiencing some issues with angr with some aarch64 binaries, you ll
experience similar problems with karonte too on the same binaries.
